# Autogenerated wrapper script for ESBMC_jll for powerpc64le-linux-gnu-cxx11-llvm_version+18
export esbmc

using Clang_jll
using z3_jll
using boost_jll
using GMP_jll
using Zlib_jll
using CompilerSupportLibraries_jll
using yaml_cpp_jll
JLLWrappers.@generate_wrapper_header("ESBMC")
JLLWrappers.@declare_executable_product(esbmc)
function __init__()
    JLLWrappers.@generate_init_header(Clang_jll, z3_jll, boost_jll, GMP_jll, Zlib_jll, CompilerSupportLibraries_jll, yaml_cpp_jll)
    JLLWrappers.@init_executable_product(
        esbmc,
        "bin/esbmc",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
